### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by dyontalsma** [walkero-gr/aiostreams#4]
It can be me, but I do not get it running. It says invalid syntax. Any help?

**Comment by walkero-gr** [comment]
Have you tried to use python in front?
i.e python youtube.py -h

**Comment by dyontalsma** [comment]
No it doesnt work it said:
File "C:\Users\Administrator\Desktop\aiostreams-master (1)\aiostreams-master\twitch.py", line 55
    except URLError, e:
                   ^
Kind regards,

Dyon Talsma

Van: George Sokianos <notifications@github.com>
Beantwoorden - Aan: walkero-gr/aiostreams <reply@reply.github.com>
Datum: donderdag 28 januari 2021 om 19:04
Aan: walkero-gr/aiostreams <aiostreams@noreply.github.com>
CC: dyontalsma <talsmadyon@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [walkero-gr/aiostreams] Doesnt work (#4)


Have you tried to use python in front?
i.e python youtube.py -h

**Comment by walkero-gr** [comment]
Which python version are you using?

**Comment by walkero-gr** [comment]
@dyontalsma 
It seems that you are using a newer version of python, possibly version 3. The aiostreams scripts are made to work with python 2.
